CREATE TABLE `orders` (
	`id` text PRIMARY KEY NOT NULL,
	`source` text NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`customer_name` text NOT NULL,
	`mobile` text NOT NULL,
	`address_line1` text NOT NULL,
	`address_line2` text DEFAULT '' NOT NULL,
	`landmark` text DEFAULT '' NOT NULL,
	`pincode` text NOT NULL,
	`city` text NOT NULL,
	`state` text NOT NULL,
	`items_json` text NOT NULL,
	`subtotal` integer NOT NULL,
	`shipping` integer DEFAULT 0 NOT NULL,
	`total` integer NOT NULL,
	`payment_status` text DEFAULT 'pending' NOT NULL,
	`note` text DEFAULT '' NOT NULL,
	`created_at` text NOT NULL
);
